server:
  port: 8001
  servlet:
    context-path: /consumer

spring:
  application:
    name: consumer

eureka:
  instance:
    prefer-ip-address: true
    instance-id:  ${spring.application.name}(${spring.cloud.client.ip-address}:${server.port})
    lease-renewal-interval-in-seconds: 10
  client:
    service-url:
      defaultZone:  http://localhost:9001/eureka/

logging:
  config:
    classpath: log4j2.yml

feign:
  hystrix:
    enabled: false