server:
  port: 9003
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/pq1518110364/spring-cloud-conifig-demo.git  # 远程git仓库的地址
          search-paths: zuul

eureka:
  instance:
    prefer-ip-address: true
    instance-id:  ${spring.application.name}(${spring.cloud.client.ip-address}:${server.port})
    lease-renewal-interval-in-seconds: 10
  client:
    service-url:
      #defaultZone:  http://localhost:9001/eureka/
      defaultZone:  http://192.168.56.134:9001/eureka/