spring:
  application:
    name: config
  cloud:
    config:
      server:
           git:
            uri: https://github.com/pq1518110364/spring-cloud-demo.git  # 远程git仓库的地址
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9001/eureka/

server:
  port: 9003