server:
  port: ${PORT:9001} #服务端口
spring:
  application:
    name: govern
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: ${EUREKA_SERVER:http://${eureka.instance.hostname}:9002/eureka/}
  server:
      enable‐self‐preservation: false #是否开启自我保护模式
      eviction‐interval‐timer‐in‐ms: 60000 #服务注册表清理间隔(单位毫秒，默认是60*1000)

logging:
  config:
    classpath: log4j2.yml

